name: Build Terraform Manual

# Controls when the action will run. 
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout repo
      - uses: actions/checkout@v2

      # get docker version
      - name: build last 5 terraform versions
        run: /bin/sh build.sh
